// NOT USED — kept only as reference/seed data. The live store
// (features/rxrfqs/hooks/use-rxrfq-data.ts) now reads from Supabase.
// Note: FACILITIES below was RxRFQ's own separate mock facility list
// (ids "1".."15"), disconnected from features/profile's real facilities.
// The live store now resolves facilities from the same shared `facilities`
// table everything else uses.

import { RxRfqMarketPlaceData, RxRfqResponseData, RxRfqResponseItem } from "@/features/rxrfqs/types/rxrfqs.types";

export type Facility = {
  id: string;
  name: string;
  location: string;
};

export const FACILITIES: Facility[] = [
  { id: "1", name: "Tema Pharmacy", location: "Accra" },
  { id: "2", name: "Korle-Bu Dispensary", location: "Accra" },
  { id: "3", name: "CityMed Clinic", location: "Kumasi" },
  { id: "4", name: "Trust Hospital Pharmacy", location: "Accra" },
  { id: "5", name: "New Pharm Ltd", location: "Takoradi" },
  { id: "6", name: "Ghana Med Supplies", location: "Tamale" },
  { id: "7", name: "Eastern Pharma Depot", location: "Koforidua" },
  { id: "8", name: "Sante Logistique", location: "Accra" },
  { id: "9", name: "Komfo Anokye Teaching Hospital", location: "Kumasi" },
  { id: "10", name: "Ridge Hospital Pharmacy", location: "Accra" },
  { id: "11", name: "Batsona Clinic", location: "Tema" },
  { id: "12", name: "Tamale Central Pharmacy", location: "Tamale" },
  { id: "13", name: "Airport Medical Centre", location: "Accra" },
  { id: "14", name: "Koforidua Regional Hospital", location: "Koforidua" },
  { id: "15", name: "Ho Municipal Dispensary", location: "Ho" },
];

export const RFQ_MOCK_DATA: RxRfqMarketPlaceData[] = [
  {
    id: "1",
    code: "RFQ-AP-001",
    facilityId: "1",
    categories: ["medication"],
    publishedAt: new Date("2025-06-01T09:00:00"),
    createdAt: new Date("2025-05-30T10:00:00"),
    createdBy: "Lex",
    productCount: 3,
    responseCount: 1,
    description: "Routine OTC restock for cold and pain relief products.",
    termsOfService: "Lorem ipsum dolor sit amet",
    incoterms: "CIP",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 5 * 86400000),
    minShelfLifeMonths: 12,
    strictMinShelfLife: false,
    deliveryDate: new Date(Date.now() + 10 * 86400000),
    comment: "Prefer branded variants where available.",
    isActive: false,
    status: "draft",
    items: [
      {
        id: "1",
        productId: "p30",
        quantity: 1,
        uom: "PACK",
        allowAlternatives: true,
        comment: "Any manufacturer accepted.",
      },
      {
        id: "2",
        productId: "p33",
        quantity: 10,
        uom: "PACK",
        allowAlternatives: false,
      },
      {
        id: "3",
        productId: "p36",
        quantity: 10,
        uom: "PACK",
        allowAlternatives: false,
      },
    ],
    visibilityScope: "All",
    visibilityRules: [],
  },
  {
    id: "2",
    code: "RFQ-KM-002",
    facilityId: "2",
    categories: ["medication", "surgical"],
    publishedAt: new Date("2025-06-03T08:30:00"),
    createdAt: new Date("2025-06-02T14:00:00"),
    createdBy: "Adwoa",
    productCount: 4,
    responseCount: 3,
    description:
      "Urgent surgical consumables and antibiotics for ward restock.",
    termsOfService: "Payment within 30 days of delivery.",
    incoterms: "DAP",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 2 * 86400000),
    minShelfLifeMonths: 18,
    strictMinShelfLife: true,
    deliveryDate: new Date(Date.now() + 4 * 86400000),
    comment: "Strict shelf life enforced — no exceptions.",
    isActive: true,
    status: "published",
    items: [
      {
        id: "1",
        productId: "p4",
        quantity: 50,
        uom: "BOX",
        allowAlternatives: true,
      },
      {
        id: "2",
        productId: "p35",
        quantity: 20,
        uom: "BOX",
        allowAlternatives: false,
      },
      {
        id: "3",
        productId: "p19",
        quantity: 100,
        uom: "PCS",
        allowAlternatives: false,
      },
      {
        id: "4",
        productId: "p29",
        quantity: 30,
        uom: "BAG",
        allowAlternatives: true,
        comment: "Any registered brand.",
      },
    ],
    visibilityScope: "Restricted",
    visibilityRules: [{ ruleType: "Region", region: "Greater Accra" }],
  },
  {
    id: "3",
    code: "RFQ-CT-003",
    facilityId: "3",
    categories: ["laboratory"],
    publishedAt: new Date("2025-06-05T11:00:00"),
    createdAt: new Date("2025-06-04T09:15:00"),
    createdBy: "Kofi",
    productCount: 2,
    responseCount: 0,
    description: "Lab reagents for routine blood chemistry panel.",
    termsOfService: "Delivery must include NAFDAC-certified COA.",
    incoterms: "EXW",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 7 * 86400000),
    minShelfLifeMonths: 6,
    strictMinShelfLife: true,
    deliveryDate: new Date(Date.now() + 14 * 86400000),
    comment: "Cold-chain delivery required.",
    isActive: true,
    status: "published",
    items: [
      {
        id: "1",
        productId: "p18",
        quantity: 5,
        uom: "KIT",
        allowAlternatives: false,
      },
      {
        id: "2",
        productId: "p11",
        quantity: 5,
        uom: "KIT",
        allowAlternatives: false,
      },
    ],
    visibilityScope: "All",
    visibilityRules: [],
  },
  {
    id: "4",
    code: "RFQ-TS-004",
    facilityId: "4",
    categories: ["medication", "nutrition"],
    publishedAt: new Date(),
    createdAt: new Date("2025-06-07T16:45:00"),
    createdBy: "Ama",
    productCount: 5,
    responseCount: 0,
    description: "Monthly therapeutic nutrition and vitamins procurement.",
    termsOfService: "Lorem ipsum dolor sit amet",
    incoterms: "CIF",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 10 * 86400000),
    minShelfLifeMonths: 12,
    strictMinShelfLife: false,
    deliveryDate: new Date(Date.now() + 16 * 86400000),
    comment: "",
    isActive: false,
    status: "draft",
    items: [
      {
        id: "1",
        productId: "p16",
        quantity: 20,
        uom: "BOX",
        allowAlternatives: true,
      },
      {
        id: "2",
        productId: "p15",
        quantity: 15,
        uom: "BOX",
        allowAlternatives: true,
      },
      {
        id: "3",
        productId: "p37",
        quantity: 10,
        uom: "BOX",
        allowAlternatives: true,
      },
      {
        id: "4",
        productId: "p39",
        quantity: 12,
        uom: "BTL",
        allowAlternatives: false,
      },
      {
        id: "5",
        productId: "p31",
        quantity: 50,
        uom: "CARTON",
        allowAlternatives: false,
        comment: "For therapeutic feeding programme.",
      },
    ],
    visibilityScope: "All",
    visibilityRules: [],
  },
  {
    id: "5",
    code: "RFQ-NP-005",
    facilityId: "5",
    categories: ["medication"],
    publishedAt: new Date("2025-05-20T07:00:00"),
    createdAt: new Date("2025-05-18T12:00:00"),
    createdBy: "Kwesi",
    productCount: 3,
    responseCount: 5,
    description: "Antihypertensive and diabetes management restock.",
    termsOfService: "Full payment upfront required.",
    incoterms: "DAP",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() - 2 * 86400000),
    minShelfLifeMonths: 24,
    strictMinShelfLife: true,
    deliveryDate: new Date(Date.now() + 3 * 86400000),
    comment: "Quotes received and under review.",
    isActive: false,
    status: "closed",
    items: [
      {
        id: "1",
        productId: "p2",
        quantity: 30,
        uom: "BOX",
        allowAlternatives: false,
      },
      {
        id: "2",
        productId: "p23",
        quantity: 40,
        uom: "BOX",
        allowAlternatives: true,
        comment: "Generic accepted.",
      },
      {
        id: "3",
        productId: "p21",
        quantity: 20,
        uom: "BOX",
        allowAlternatives: false,
      },
    ],
    visibilityScope: "Restricted",
    visibilityRules: [{ ruleType: "Facility Type", facilityType: "Wholesale" }],
  },
  {
    id: "6",
    code: "RFQ-GH-006",
    facilityId: "6",
    categories: ["surgical", "consumables"],
    publishedAt: new Date("2025-06-08T10:00:00"),
    createdAt: new Date("2025-06-07T08:00:00"),
    createdBy: "Ibrahim",
    productCount: 6,
    responseCount: 2,
    description:
      "Wound care and dressing consumables for rural clinic network.",
    termsOfService: "Delivery to multiple drop-off points required.",
    incoterms: "DDP",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 6 * 86400000),
    minShelfLifeMonths: 12,
    strictMinShelfLife: false,
    deliveryDate: new Date(Date.now() + 12 * 86400000),
    comment: "Bulk discount expected for quantities above 100 units.",
    isActive: true,
    status: "published",
    items: [
      {
        id: "1",
        productId: "p17",
        quantity: 200,
        uom: "PCS",
        allowAlternatives: false,
      },
      {
        id: "2",
        productId: "p25",
        quantity: 50,
        uom: "ROLL",
        allowAlternatives: true,
      },
      {
        id: "3",
        productId: "p12",
        quantity: 100,
        uom: "PCS",
        allowAlternatives: true,
      },
      {
        id: "4",
        productId: "p7",
        quantity: 20,
        uom: "BTL",
        allowAlternatives: false,
      },
      {
        id: "5",
        productId: "p10",
        quantity: 30,
        uom: "ROLL",
        allowAlternatives: true,
      },
      {
        id: "6",
        productId: "p14",
        quantity: 500,
        uom: "PCS",
        allowAlternatives: false,
      },
    ],
    visibilityScope: "All",
    visibilityRules: [],
  },
  {
    id: "7",
    code: "RFQ-EP-007",
    facilityId: "7",
    categories: ["medication"],
    publishedAt: new Date("2025-06-09T09:00:00"),
    createdAt: new Date("2025-06-08T15:30:00"),
    createdBy: "Yaa",
    productCount: 4,
    responseCount: 1,
    description: "Antimalarial and antiparasitic quarterly restock.",
    termsOfService: "Lorem ipsum dolor sit amet",
    incoterms: "CIP",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 8 * 86400000),
    minShelfLifeMonths: 18,
    strictMinShelfLife: true,
    deliveryDate: new Date(Date.now() + 15 * 86400000),
    comment: "WHO-prequalified manufacturers preferred.",
    isActive: true,
    status: "published",
    items: [
      {
        id: "1",
        productId: "p5",
        quantity: 60,
        uom: "BOX",
        allowAlternatives: false,
      },
      {
        id: "2",
        productId: "p6",
        quantity: 20,
        uom: "VIAL",
        allowAlternatives: false,
      },
      {
        id: "3",
        productId: "p1",
        quantity: 25,
        uom: "BOX",
        allowAlternatives: true,
      },
      {
        id: "4",
        productId: "p24",
        quantity: 30,
        uom: "BOX",
        allowAlternatives: true,
        comment: "Generic accepted.",
      },
    ],
    visibilityScope: "All",
    visibilityRules: [],
  },
  {
    id: "8",
    code: "RFQ-SL-008",
    facilityId: "8",
    categories: ["equipment", "consumables"],
    publishedAt: new Date(),
    createdAt: new Date("2025-06-10T11:00:00"),
    createdBy: "Nana",
    productCount: 3,
    responseCount: 0,
    description:
      "Diagnostic equipment and accessories for new outpatient unit.",
    termsOfService: "Warranty documentation required on delivery.",
    incoterms: "CIF",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 14 * 86400000),
    minShelfLifeMonths: 0,
    strictMinShelfLife: false,
    deliveryDate: new Date(Date.now() + 21 * 86400000),
    comment: "Installation and calibration support required.",
    isActive: false,
    status: "draft",
    items: [
      {
        id: "1",
        productId: "p13",
        quantity: 10,
        uom: "PCS",
        allowAlternatives: true,
        comment: "SpO2 + heart rate required.",
      },
      {
        id: "2",
        productId: "p28",
        quantity: 10,
        uom: "PCS",
        allowAlternatives: true,
      },
      {
        id: "3",
        productId: "p8",
        quantity: 5,
        uom: "PCS",
        allowAlternatives: false,
      },
    ],
    visibilityScope: "Restricted",
    visibilityRules: [{ ruleType: "Region", region: "Greater Accra" }],
  },
  {
    id: "9",
    code: "RFQ-AP-009",
    categories: ["antibiotics", "critical-care"],
    publishedAt: new Date(),
    createdAt: new Date(),
    createdBy: "Sarah",
    productCount: 2,
    responseCount: 0,
    facilityId: "9",
    description: "Procurement of essential antibiotics for pediatric ward.",
    termsOfService: "Standard institutional procurement terms apply.",
    incoterms: "DDP",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 3 * 86400000),
    minShelfLifeMonths: 18,
    strictMinShelfLife: true,
    deliveryDate: new Date(Date.now() + 7 * 86400000),
    comment: "High priority requirement.",
    isActive: true,
    status: "published",
    items: [
      {
        id: "1",
        productId: "p3",
        quantity: 50,
        uom: "BOTTLE",
        allowAlternatives: true,
        comment: "Must be sugar-free if possible.",
      },
      {
        id: "2",
        productId: "p9",
        quantity: 100,
        uom: "BOX",
        allowAlternatives: true,
      },
    ],
    visibilityScope: "All",
    visibilityRules: [],
  },
  {
    id: "10",
    code: "RFQ-AP-010",
    categories: ["medication"],
    publishedAt: new Date(),
    createdAt: new Date(),
    createdBy: "Lex",
    productCount: 3,
    responseCount: 1,
    facilityId: "10",
    description: "Urgent restocking of basic analgesics and cough remedies.",
    termsOfService: "Payment upon delivery within 14 business days.",
    incoterms: "CIP",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 5 * 86400000),
    minShelfLifeMonths: 12,
    strictMinShelfLife: false,
    deliveryDate: new Date(Date.now() + 10 * 86400000),
    comment: "Please ensure all packaging is intact.",
    isActive: false,
    status: "draft",
    items: [
      {
        id: "1",
        productId: "p30",
        quantity: 1,
        uom: "PACK",
        allowAlternatives: true,
        comment: "Generic alternatives accepted.",
      },
      {
        id: "2",
        productId: "p33",
        quantity: 10,
        uom: "PACK",
        allowAlternatives: false,
      },
      {
        id: "3",
        productId: "p36",
        quantity: 10,
        uom: "PACK",
        allowAlternatives: false,
      },
    ],
    visibilityScope: "All",
    visibilityRules: [],
  },
  {
    id: "11",
    code: "RFQ-AP-011",
    categories: ["consumables"],
    publishedAt: new Date(),
    createdAt: new Date(),
    createdBy: "John",
    productCount: 3,
    responseCount: 4,
    facilityId: "11",
    description: "Quarterly replenishment of basic medical consumables.",
    termsOfService: "50% advance, 50% upon delivery validation.",
    incoterms: "EXW",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 12 * 86400000),
    minShelfLifeMonths: 24,
    strictMinShelfLife: false,
    deliveryDate: new Date(Date.now() + 20 * 86400000),
    comment: "Bulk pricing discounts preferred.",
    isActive: true,
    status: "published",
    items: [
      {
        id: "1",
        productId: "p14",
        quantity: 500,
        uom: "PIECE",
        allowAlternatives: true,
      },
      {
        id: "2",
        productId: "p34",
        quantity: 50,
        uom: "BOX",
        allowAlternatives: true,
      },
      {
        id: "3",
        productId: "p22",
        quantity: 100,
        uom: "BOX",
        allowAlternatives: false,
        comment: "Size Medium only.",
      },
    ],
    visibilityScope: "All",
    visibilityRules: [],
  },
  {
    id: "12",
    code: "RFQ-AP-012",
    categories: ["antimalarials"],
    publishedAt: new Date(),
    createdAt: new Date(),
    createdBy: "Kwame",
    productCount: 2,
    responseCount: 2,
    facilityId: "12",
    description: "Pre-rainy season stocking of antimalarial medications.",
    termsOfService: "Net 30 payment terms.",
    incoterms: "FOB",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 6 * 86400000),
    minShelfLifeMonths: 16,
    strictMinShelfLife: true,
    deliveryDate: new Date(Date.now() + 14 * 86400000),
    comment: "Products must be FDA Ghana registered.",
    isActive: true,
    status: "published",
    items: [
      {
        id: "1",
        productId: "p5",
        quantity: 200,
        uom: "PACK",
        allowAlternatives: false,
      },
      {
        id: "2",
        productId: "p6",
        quantity: 50,
        uom: "VIAL",
        allowAlternatives: true,
      },
    ],
    visibilityScope: "All",
    visibilityRules: [],
  },
  {
    id: "13",
    code: "RFQ-AP-013",
    categories: ["chronic-care", "cardiology"],
    publishedAt: new Date(),
    createdAt: new Date(),
    createdBy: "Ellen",
    productCount: 3,
    responseCount: 0,
    facilityId: "13",
    description:
      "Sourcing for routine hypertensive and diabetic care management.",
    termsOfService: "Immediate electronic funds transfer upon delivery check.",
    incoterms: "CIP",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 4 * 86400000),
    minShelfLifeMonths: 12,
    strictMinShelfLife: false,
    deliveryDate: new Date(Date.now() + 8 * 86400000),
    comment: "Cold chain logistics required for insulin items.",
    isActive: false,
    status: "draft",
    items: [
      {
        id: "1",
        productId: "p2",
        quantity: 300,
        uom: "PACK",
        allowAlternatives: true,
      },
      {
        id: "2",
        productId: "p23",
        quantity: 500,
        uom: "PACK",
        allowAlternatives: true,
      },
      {
        id: "3",
        productId: "p26",
        quantity: 40,
        uom: "BOX",
        allowAlternatives: false,
      },
    ],
    visibilityScope: "All",
    visibilityRules: [],
  },
  {
    id: "14",
    code: "RFQ-AP-014",
    categories: ["anesthetics", "surgery"],
    publishedAt: new Date(),
    createdAt: new Date(),
    createdBy: "Mavis",
    productCount: 2,
    responseCount: 0,
    facilityId: "14",
    description: "Urgent surgical theater replenishment.",
    termsOfService: "Government institutional framework contract matching.",
    incoterms: "CIP",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 2 * 86400000),
    minShelfLifeMonths: 24,
    strictMinShelfLife: true,
    deliveryDate: new Date(Date.now() + 4 * 86400000),
    comment: "Extremely time-sensitive request.",
    isActive: true,
    status: "published",
    items: [
      {
        id: "1",
        productId: "p32",
        quantity: 200,
        uom: "VIAL",
        allowAlternatives: false,
      },
      {
        id: "2",
        productId: "p20",
        quantity: 100,
        uom: "VIAL",
        allowAlternatives: true,
      },
    ],
    visibilityScope: "Restricted",
    visibilityRules: [
      {
        ruleType: "Region",
        region: "Accra",
      },
    ],
  },
  {
    id: "15",
    code: "RFQ-AP-015",
    categories: ["vitamins"],
    publishedAt: new Date(),
    createdAt: new Date(),
    createdBy: "Lex",
    productCount: 2,
    responseCount: 1,
    facilityId: "15",
    description: "Procurement of dietary supplements and multivitamins.",
    termsOfService: "Standard local council terms.",
    incoterms: "DDP",
    currency: "GHS",
    submissionDeadline: new Date(Date.now() + 8 * 86400000),
    minShelfLifeMonths: 10,
    strictMinShelfLife: false,
    deliveryDate: new Date(Date.now() + 15 * 86400000),
    comment: "Syrup formats preferred for pediatric use.",
    isActive: true,
    status: "published",
    items: [
      {
        id: "1",
        productId: "p27",
        quantity: 150,
        uom: "BOTTLE",
        allowAlternatives: true,
      },
      {
        id: "2",
        productId: "p38",
        quantity: 80,
        uom: "PACK",
        allowAlternatives: true,
      },
    ],
    visibilityScope: "All",
    visibilityRules: [],
  },
];

const RESPONSE_VENDOR_POOL = [
  "MedPlus Distributors",
  "Accra Pharma Wholesale",
  "GlobalRx Supplies",
  "Northstar Healthcare Logistics",
  "PrimeCare Pharma Ltd",
  "Sahel Medical Traders",
];

function generateMockResponseItems(
  rfqItems: RxRfqMarketPlaceData["items"],
  seed: number,
): RxRfqResponseItem[] {
  return rfqItems.map((item, idx) => {
    const rate = 12.5 + ((seed + idx) % 7) * 3.75;
    const quantity = item.quantity;
    return {
      id: `${idx + 1}`,
      rfqItemId: item.id,
      productId: item.productId,
      quantity,
      rate: Math.round(rate * 100) / 100,
      amount: Math.round(rate * quantity * 100) / 100,
      offeredAlternative: false,
    };
  });
}

function generateMockResponses(): RxRfqResponseData[] {
  const responses: RxRfqResponseData[] = [];

  RFQ_MOCK_DATA.forEach((rfq) => {
    for (let i = 0; i < rfq.responseCount; i++) {
      const seed = Number(rfq.id) * 10 + i;
      const items = generateMockResponseItems(rfq.items, seed);
      const totalItemsAmount = items.reduce((sum, it) => sum + it.amount, 0);

      const additionalCosts: RxRfqAdditionalCostItem[] = [
        {
          id: "1",
          costType: "delivery",
          description: "Delivery to facility",
          amount: 50 + (seed % 5) * 10,
          isRequired: true,
        },
      ];
      const totalRequiredCosts = additionalCosts
        .filter((c) => c.isRequired)
        .reduce((sum, c) => sum + c.amount, 0);
      const totalOptionalCosts = additionalCosts
        .filter((c) => !c.isRequired)
        .reduce((sum, c) => sum + c.amount, 0);

      const submittedAt = new Date(
        new Date(rfq.publishedAt).getTime() +
          (i + 1) * 6 * 60 * 60 * 1000,
      );

      responses.push({
        id: `${rfq.id}-r${i + 1}`,
        rfqId: rfq.id,
        vendorFacility: RESPONSE_VENDOR_POOL[seed % RESPONSE_VENDOR_POOL.length],
        status: "submitted",
        quoteValidUntil: new Date(
          submittedAt.getTime() + 14 * 24 * 60 * 60 * 1000,
        ),
        estimatedDeliveryDate: new Date(
          submittedAt.getTime() + 5 * 24 * 60 * 60 * 1000,
        ),
        incoterms: rfq.incoterms,
        currency: rfq.currency,
        paymentTerms: "Net 30",
        items,
        additionalCosts,
        createdAt: submittedAt,
        submittedAt,
        createdBy: RESPONSE_VENDOR_POOL[seed % RESPONSE_VENDOR_POOL.length],
        totalItemsAmount,
        totalRequiredCosts,
        totalOptionalCosts,
        grandTotal: totalItemsAmount + totalRequiredCosts + totalOptionalCosts,
      });
    }
  });

  return responses;
}

